In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([1,2,3,4])
b = tf.constant([3,4,5,6])

product = tf.multiply(a,b)
print(product)

Tensor("Mul:0", shape=(4,), dtype=int32)


In [4]:
#To run the session do this
sesh = tf.Session()

print(sesh.run(product))

sesh.close()

[ 3  8 15 24]


In [5]:
# To run the same session interactivelt.

with tf.Session() as sesh:
    
    print(sesh.run(product))


[ 3  8 15 24]


In [8]:
# passing configuration options
# Log device placement
config=tf.ConfigProto(log_device_placement=True)
# For allowing system to execute on CPU when GPU is not available or instructions cannot be placed on GPU.
config=tf.ConfigProto(allow_soft_placement=True)
 
with tf.Session() as sesh:
    print(sesh.run(product))
    

[ 3  8 15 24]


In [ ]:
# create the Graph

inputs = tf.placeholder(dtype = tf.float32, shape = [None,28,28,3])
labels = tf.placeholder(dtype = tf.int32, shape = [None,28,28,3])

conv1 = tf.nn.conv2d(inputs=input=inputs,)